
export const mockAllVisitSessions = [
  {
    visitId: "VISIT-2024-001",
    visitDate: "Today",
    visitTime: "2:00 PM - 4:30 PM",
    tableNo: 5,
    totalOrders: 3,
    totalAmount: 3360,
    orders: [
      {
        id: "ORD-001",
        items: [
          {
            name: "Paneer Bhuna Masala",
            quantity: 2,
            price: 380,
            image:
              "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmupHn07P1YrvEjxzZymu5UUsk5ChCsN3L3AZiIzqJCiPHEXWvVfUG0R9IodFr_WBhteM&usqp=CAU",
            category: "Main Course",
            spiceLevel: "Medium",
          },
          {
            name: "Butter Naan",
            quantity: 3,
            price: 80,
            image: "https://orders.popskitchen.in/storage/2024/09/image-69.png",
            category: "Bread",
            spiceLevel: "Mild",
          },
          {
            name: "Aangan Rasmalai",
            quantity: 1,
            price: 250,
            image: "https://images.jdmagicbox.com/justdial/icons/website/dishes/rasmalai.jpg",
            category: "Dessert",
            spiceLevel: "Sweet",
          },
        ],
        totalAmount: 1290,
        status: "delivered",
        orderTime: "2:30 PM",
        estimatedTime: "Delivered",
        rating: 5,
      },
      {
        id: "ORD-002",
        items: [
          {
            name: "Dal Bati Churma",
            quantity: 1,
            price: 450,
            image:
              "https://assets.cntraveller.in/photos/64c77e630d528c30692aaa58/4:3/w_1440,h_1080,c_limit/dal%20bhaati%20lead.jpeg",
            category: "Traditional",
            spiceLevel: "Medium",
          },
          {
            name: "Masala Dosa",
            quantity: 2,
            price: 150,
            image: "https://delishglobe.com/wp-content/uploads/2024/09/Masala-dosa-1.png",
            category: "South Indian",
            spiceLevel: "Medium",
          },
          {
            name: "Kulfi Falooda",
            quantity: 2,
            price: 220,
            image: "https://www.secondrecipe.com/wp-content/uploads/2021/02/kulfi-falooda-recipe.jpg",
            category: "Dessert",
            spiceLevel: "Sweet",
          },
        ],
        totalAmount: 1190,
        status: "delivered",
        orderTime: "3:15 PM",
        estimatedTime: "Delivered",
        rating: 4,
      },
      {
        id: "ORD-003",
        items: [
          {
            name: "Chicken 65",
            quantity: 1,
            price: 320,
            image: "https://i.ytimg.com/vi/afaP90FH-MA/maxresdefault.jpg",
            category: "Appetizer",
            spiceLevel: "Hot",
          },
          {
            name: "Butter Chicken",
            quantity: 1,
            price: 420,
            image:
              "https://www.allrecipes.com/thmb/8L5gq8V7Kyl3qfoDe5vhCU_rvZI=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/AR-141169-Easy-Indian-Butter-Chicken-DDMFS-4x3-beauty-588ff54d1e0f4a0788906e851e27d540.jpg",
            category: "Main Course",
            spiceLevel: "Medium",
          },
          {
            name: "Tandoori Roti",
            quantity: 4,
            price: 60,
            image: "https://static.toiimg.com/thumb/75542650.cms?width=800&height=800&imgsize=2236995",
            category: "Bread",
            spiceLevel: "Mild",
          },
        ],
        totalAmount: 880,
        status: "preparing",
        orderTime: "4:00 PM",
        estimatedTime: "15 mins",
      },
    ],
  },
  {
    visitId: "VISIT-2024-002",
    visitDate: "Yesterday",
    visitTime: "7:00 PM - 9:00 PM",
    tableNo: 2,
    totalOrders: 2,
    totalAmount: 2500,
    orders: [
      {
        id: "ORD-004",
        items: [
          {
            name: "Chicken Biryani",
            quantity: 2,
            price: 500,
            image: "https://www.licious.in/blog/wp-content/uploads/2022/06/chicken-biryani-recipe.jpg",
            category: "Main Course",
            spiceLevel: "Hot",
          },
          {
            name: "Raita",
            quantity: 2,
            price: 100,
            image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/05/boondi-raita-recipe.jpg",
            category: "Side Dish",
            spiceLevel: "Mild",
          },
        ],
        totalAmount: 1200,
        status: "delivered",
        orderTime: "7:30 PM",
        estimatedTime: "Delivered",
        rating: 5,
      },
      {
        id: "ORD-005",
        items: [
          {
            name: "Veg Thali",
            quantity: 1,
            price: 650,
            image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/03/north-indian-thali.jpg",
            category: "Thali",
            spiceLevel: "Medium",
          },
          {
            name: "Gulab Jamun",
            quantity: 3,
            price: 220,
            image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/03/gulab-jamun-recipe.jpg",
            category: "Dessert",
            spiceLevel: "Sweet",
          },
        ],
        totalAmount: 1310, // Adjusted to make total 2510
        status: "delivered",
        orderTime: "8:00 PM",
        estimatedTime: "Delivered",
        rating: 4,
      },
    ],
  },
  {
    visitId: "VISIT-2024-003",
    visitDate: "2 days ago",
    visitTime: "1:00 PM - 2:30 PM",
    tableNo: 8,
    totalOrders: 1,
    totalAmount: 750,
    orders: [
      {
        id: "ORD-006",
        items: [
          {
            name: "Veg Manchurian",
            quantity: 1,
            price: 300,
            image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/02/veg-manchurian-recipe.jpg",
            category: "Chinese",
            spiceLevel: "Medium",
          },
          {
            name: "Fried Rice",
            quantity: 1,
            price: 250,
            image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/02/veg-fried-rice-recipe.jpg",
            category: "Chinese",
            spiceLevel: "Mild",
          },
          {
            name: "Spring Rolls",
            quantity: 1,
            price: 200,
            image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/02/veg-spring-rolls-recipe.jpg",
            category: "Appetizer",
            spiceLevel: "Mild",
          },
        ],
        totalAmount: 750,
        status: "delivered",
        orderTime: "1:45 PM",
        estimatedTime: "Delivered",
        rating: 3,
      },
    ],
  },
  {
    visitId: "VISIT-2024-004",
    visitDate: "3 days ago",
    visitTime: "6:00 PM - 7:30 PM",
    tableNo: 1,
    totalOrders: 2,
    totalAmount: 1500,
    orders: [
      {
        id: "ORD-007",
        items: [
          {
            name: "Chicken Tikka Masala",
            quantity: 1,
            price: 450,
            image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/03/chicken-tikka-masala-recipe.jpg",
            category: "Main Course",
            spiceLevel: "Hot",
          },
          {
            name: "Garlic Naan",
            quantity: 2,
            price: 90,
            image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/03/garlic-naan-recipe.jpg",
            category: "Bread",
            spiceLevel: "Mild",
          },
        ],
        totalAmount: 630,
        status: "delivered",
        orderTime: "6:45 PM",
        estimatedTime: "Delivered",
        rating: 4,
      },
      {
        id: "ORD-008",
        items: [
          {
            name: "Palak Paneer",
            quantity: 1,
            price: 380,
            image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/03/palak-paneer-recipe.jpg",
            category: "Main Course",
            spiceLevel: "Medium",
          },
          {
            name: "Jeera Rice",
            quantity: 1,
            price: 200,
            image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/03/jeera-rice-recipe.jpg",
            category: "Rice",
            spiceLevel: "Mild",
          },
          {
            name: "Lassi",
            quantity: 2,
            price: 145,
            image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/03/sweet-lassi-recipe.jpg",
            category: "Beverage",
            spiceLevel: "Sweet",
          },
        ],
        totalAmount: 870,
        status: "delivered",
        orderTime: "7:15 PM",
        estimatedTime: "Delivered",
        rating: 5,
      },
    ],
  },
]
